spring.jpa.show-sql=false
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.open-in-view=false

# active la prise en compte des en-têtes X-Forwarded-* par le connecteur Tomcat embarqué (via son RemoteIpValve),
# au lieu de laisser Spring Security/l'application les ignorer ou les interpréter naïvement.
# prmete d'utiliser les valeurs par défaut de tomcat
# AuthenticationController.resolveClientIp()
forward-headers-strategy=native