spring.application.name=officine

#========MYSQL CONFIGURATION FOR Spring boot 3.1 or higher =====#
spring.jpa.show-sql=true
spring.datasource.url=jdbc:mysql://localhost:3306/officine
spring.datasource.username=root
spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#========MYSQL CONFIGURATION FOR Spring boot 3.1 or higher =====#