-- Déplace quantité / prix / lot catalogue vers MOUVEMENT_STOCK (produit = référentiel seul).
-- Exécuter sur MySQL après déploiement du code correspondant.

ALTER TABLE MOUVEMENT_STOCK
  ADD COLUMN COST_PRICE NUMERIC(38, 2) NULL,
  ADD COLUMN SELL_PRICE NUMERIC(38, 2) NULL;

-- Reprise : dernier état catalogue → mouvement d'entrée par produit (si colonnes encore présentes)
INSERT INTO MOUVEMENT_STOCK (
  PRODUCT_ID, BATCH_ID, TYPE_MOUVEMENT, QUANTITE_ALGEBRIQUE,
  COST_PRICE, SELL_PRICE, DATE_MOUVEMENT, COMMENTAIRE
)
SELECT
  p.ID,
  p.BATCH_ID,
  'ENTREE',
  COALESCE(p.QUANTITY, 0),
  p.COST_PRICE,
  p.SELL_PRICE,
  NOW(),
  'Migration catalogue → mouvement'
FROM PRODUCT p
WHERE COALESCE(p.QUANTITY, 0) <> 0
   OR p.COST_PRICE IS NOT NULL
   OR p.SELL_PRICE IS NOT NULL
   OR p.BATCH_ID IS NOT NULL;

ALTER TABLE PRODUCT DROP FOREIGN KEY FK225K7E49A8B6KQ01CC04DQRUL;
ALTER TABLE PRODUCT DROP COLUMN BATCH_ID;
ALTER TABLE PRODUCT DROP COLUMN QUANTITY;
ALTER TABLE PRODUCT DROP COLUMN COST_PRICE;
ALTER TABLE PRODUCT DROP COLUMN SELL_PRICE;
