-- Bon interne : lot sélectionné au picking (central) ; traçabilité mouvements.
-- Exécuter sur la base officine après déploiement du code correspondant.

ALTER TABLE LIGNE_BON_COMMANDE_INTERNE
  ADD COLUMN BATCH_ID BIGINT NULL;

ALTER TABLE LIGNE_BON_COMMANDE_INTERNE
  ADD CONSTRAINT FK_LBCI_BATCH FOREIGN KEY (BATCH_ID) REFERENCES BATCH(ID);

ALTER TABLE MOUVEMENT_STOCK
  ADD COLUMN BATCH_ID BIGINT NULL;

ALTER TABLE MOUVEMENT_STOCK
  ADD CONSTRAINT FK_MVT_BATCH FOREIGN KEY (BATCH_ID) REFERENCES BATCH(ID);
